common/urls.py
from django.contrib import admin
from django.urls import path

from .views import user_login, report_view, order_driver_view, procces_order, report_view_today, \
    report_view_today_bs, report_view_today_bs_api, report_orders_bs_api, report_new_clients_bs_api, \
    report_for_position_bs_api, report_analysis_clients

urlpatterns = [
    # url(r'^$', views.index, name='index'),
    path('', user_login, name='user_login'),
    path('report/', report_view, name = 'report'),
    # path('report/', report_view, name = 'report'),
    path('report_today/', report_view_today, name = 'report_today'),
    path('report_today_bs/', report_view_today_bs, name = 'report_today_bs'),
    path('report_today_bs_api/', report_view_today_bs_api, name = 'report_today_bs_api'),
    path('report_orders_bs_api/', report_orders_bs_api, name = 'report_orders_bs_api'),
    path('report_new_clients_bs_api/', report_new_clients_bs_api, name = 'report_new_clients_bs_api'),
    path('report_for_position_bs_api/', report_for_position_bs_api, name = 'report_for_position_bs_api'),
    path('report_analysis_clients/', report_analysis_clients, name = 'report_analysis_clients'),
    path('admin/', admin.site.urls),
    path('order_driver/<int:id>/', order_driver_view, name='order_driver'),
    path('procces_order/', procces_order, name='procces_order'),

    # path('documents/order/add/', admin.site.urls),
    ]

water/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('api/', include('common.urls_api')),
    # path('common/', include('common.urls')),
    path('', include('common.urls')),
    # path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls'))
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

common/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label="Пользователь")
    password = forms.CharField(widget=forms.PasswordInput, label="Пароль")
    next = forms.CharField(widget=forms.HiddenInput(), required=False)

common/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect, render
from rest_framework.response import Response

import locale

from django.db.models import F, QuerySet, Sum, Count

from documents.forms import OrderForm

import datetime
from datetime import date
from datetime import datetime, timedelta
from datetime import time

from common.forms import LoginForm
from common.models import Client, Positions, Driver
from documents.models import Order, TabluarOrders

from django.db.models import Q

from .service import getData

locale.setlocale(locale.LC_ALL,'')

def index(request):
    return HttpResponse("Hello, World!")


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    if user.is_superuser:
                        login(request, user)
                        return redirect('/admin/')
                    else:
                        login(request, user)
                        return report_view(request)
                else:
                    # messages.error(request, 'Учетная запись не активна!')
                    return render(request, 'login.html', {'form': LoginForm()})
            else:
                # messages.error(request, 'Неверный логин или пароль!')
                return render(request, 'login.html', {'form': LoginForm()})
    else:
        # if request.user.is_superuser:
        #     login(request, request.user)
        #     return redirect('/admin/')

        if request.user.is_authenticated:
        #     return report_view(request)
        # else:
            return render(request, 'login.html', {'form': LoginForm()})

    return render(request, 'login.html', {'form': LoginForm()})



@login_required()
def report_view(request):
    if request.user:
        driver = Driver.objects.filter(user=request.user).first()
        if driver:
            orders = get_data_for_report(driver)
            data = {'driver': driver,
                    'orders' : orders}
            return render (request,'report_for_driver.html', data)
            # return HttpResponse("Тут должна быть информация для водителей!")
        else:
            return redirect('/admin/')

def get_data_for_report(driver):
    orders = driver.get_open_orders_full()
    data = []

    for inx, order in enumerate(orders):
        if order.date_dev != datetime.date.today():
            continue
        f = {'date':order.date,
         'client': order.client,
         'phone_number': order.client.phone_number,
         'type_pay': order.get_type_play_display(),
         'order': order,
         'order_id': order.id,
         'ref': "/order_driver/" + str(order.id) + '/',
         'number': order.number,
         'index': inx,
         'id_checkbox': 'id_checkbox_' + str(inx),
         'id_button': 'id_button_' + str(inx)
         }
        data.append(f)
    return data

# @login_required()
def report_view_today(request):

    if request.GET.get('period'):
        period = request.GET.get('period')
    else:
        period = '1'
    if period == '1':
        start = datetime.combine(date.today() - timedelta(days=1), time(17, 30, 00)) # Вчера вечер
        finish = datetime.combine(date.today(), time(8, 30, 00)) # сегодня утро
        period_str = '17:30 - 8:30'
    elif period == '2':
        start = datetime.combine(date.today(), time(8, 30, 00)) # Сегодня утро
        finish = datetime.combine(date.today(), time(17, 30, 00)) # Сегодня вечер
        period_str = '8:30 - 17:30'

    drivers = Driver.objects.all()
    data_dr = {}
    for driver in drivers:
        orders = driver.get_open_orders_detalis(start, finish)
        if not orders:
            continue
        data = []

        for inx, row in enumerate(orders):
            # if order.date_dev != datetime.date.today():
            #     continue
            f = {'num': inx + 1,
                 'date_dev': row.order.date_dev,
                 'district': row.order.client.district,
                 'address': row.order.client,
                 'phone_number': row.order.client.phone_number,
                 'position': row.position,
                 'quantity': row.quantity,
                 'amount': row.amount,
                 'comment': row.order.comment if row.order.comment != None else '' ,
                 'period_str': period_str ,
                 }
            data.append(f)
        key = driver.name
        data_dr[key] = data

    # Теперь для незаполненных водителей
    orders = TabluarOrders.objects.filter(order__client__driver=None,  order__date__gte=start, order__date__lte=finish).order_by('order__client__district')
    # orders = TabluarOrders.objects.filter(order__client__driver=None).order_by('order__client__district')
    if not orders:
        return render(request,'report_today.html',{'data' : data_dr})
    data = []

    for inx, row in enumerate(orders):
        # if order.date_dev != datetime.date.today():
        #     continue
        f = {'num': inx + 1,
             'date_dev': row.order.date_dev,
             'district': row.order.client.district,
             'address': row.order.client,
             'phone_number': row.order.client.phone_number,
             'position': row.position,
             'quantity': row.quantity,
             'amount': row.amount,
             'comment': row.order.comment if row.order.comment != None else '',
             'period_str': period_str,
             }
        data.append(f)
    # key = driver.name +' '+ datetime.date.today().strftime('%d.%m')
    key = "Не установлен"
    data_dr[key] = data
    return render(request,'report_today.html',{'data' : data_dr})

def report_view_today_bs(request):

    if request.GET.get('period'):
        period = request.GET.get('period')
    else:
        period = '1'
    if period == '1':
        start = datetime.combine(date.today() - timedelta(days=1), time(17, 30, 00))  # Вчера вечер
        finish = datetime.combine(date.today(), time(8, 30, 00))  # сегодня утро
        period_str = '17:30 - 8:30'
    elif period == '2':
        start = datetime.combine(date.today(), time(8, 30, 00))  # Сегодня утро
        finish = datetime.combine(date.today(), time(17, 30, 00))  # Сегодня вечер
        period_str = '8:30 - 17:30'
    # data = TabluarOrders.objects.filter(order__date__gte=start,
    #                                     order__date__lte=finish).order_by('order__client__district')
    data = TabluarOrders.objects.values(date_dev=F('order__date_dev'),
                                        driver=F('order__client__driver__name'),
                                        district=F('order__client__district__name'),
                                        address=F('order__client__name'),
                                        phone_number=F('order__client__phone_number'),
                                        position_=F('position__name'),
                                        quantity_=F('quantity'),
                                        amount_=F('amount'),
                                        comment=F('order__comment')
                                        )#.filter(order__date__gte=start,
                                        #order__date__lte=finish).order_by('driver')

    for val in data:
        # val['date_dev'] = str(val['date_dev'])
        if not val['district']:
            val['district'] = "Не установлен"

        if not val['driver']:
            val['driver'] = "Не установлен"

    positions = Positions.objects.values('pk','name')
    return render(request, 'report_today_bs2.html', {'data' : data, 'param': period, 'positions': list(positions)})

def report_view_today_bs_api(request):

    general = False
    if request.GET.get('period') == 'general':
        general = True

    start = ''
    finish = ''
    status_order = ''

    if request.GET.get('date_dev'):
        date_dev_str = request.GET.get('date_dev')
        if date_dev_str == 'Сегодня':
            date_dev_str = datetime.today().strftime('%d/%m/%Y')
    else:
        start_str = datetime.today().strftime('%d/%m/%Y')

    date_dev = datetime.strptime(date_dev_str, "%d/%m/%Y")

    if not general:
        if request.GET.get('period'):
            period = request.GET.get('period')
        else:
            period = '1'
        if period == '1':
            start = datetime.combine(date_dev.date() - timedelta(days=1), time(17, 00, 00))  # Вчера вечер
            finish = datetime.combine(date_dev.date(), time(8, 30, 00))  # сегодня утро
            period_str = '17:30 - 8:30'
        elif period == '2':
            start = datetime.combine(date_dev.date(), time(8, 30, 00))  # Сегодня утро
            finish = datetime.combine(date_dev.date(), time(17, 00, 00))  # Сегодня вечер
            period_str = '8:30 - 17:30'

    status = '1'
    if request.GET.get('status'):
        status = request.GET.get('status')
        if status == '2':
            status_order = Order.STATUS_TYPE_NEW
        elif status == '3':
            status_order = Order.STATUS_TYPE_postponed
        elif status == '4':
            status_order = Order.STATUS_TYPE_COMPLETED




    # data = TabluarOrders.objects.filter(order__date__gte=start,
    #                                     order__date__lte=finish).order_by('order__client__district')
    # if general:
    #     data = TabluarOrders.objects.values(date_dev=F('order__date_dev'),
    #                                         driver=F('order__client__driver__name'),
    #                                         district=F('order__client__district__name'),

common/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title> Отчёты </title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
{#  <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css">#}
  <link rel="stylesheet" href="https://unpkg.com/@fortawesome/fontawesome-free@5.12.1/css/all.min.css">
  <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
<script src="/static/admin/js/vendor/jquery/jquery.js"></script>
  <script src="/static/admin/js/jquery.init.js"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />
  {% block extra_css %} {% endblock %}

</head>
<body>
{% csrf_token %}
<div class="page-container container">
  {% block page %}{% endblock %}
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
        integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
        crossorigin="anonymous"></script>



  <script src="https://unpkg.com/tableexport.jquery.plugin/tableExport.min.js"></script>
  <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
  <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table-locale-ru-RU.min.js"></script>
  <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/export/bootstrap-table-export.min.js"></script>

{#<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>#}
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.js"></script>

{% block extra_js %}{% endblock %}
</body>
</html>

common/templates/login.html
{% load static %}

<!DOCTYPE html>

<html lang="ru-ru" dir="ltr">
<head>
<title>Войти | Административный сайт Django</title>
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">

  <link rel="stylesheet" type="text/css" href="/static/admin/css/nav_sidebar.css">
  <script src="/static/admin/js/nav_sidebar.js" defer></script>

<link rel="stylesheet" type="text/css" href="/static/admin/css/login.css">

    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">

<meta name="robots" content="NONE,NOARCHIVE">
</head>

<body class=" login"
  data-admin-utc-offset="18000">
<!-- Container -->
<div id="container">

    <!-- Header -->
    <div id="header">
        <div id="branding">

<h1 id="site-name"><a href="/">Онлайн заказ воды</a></h1>

        </div>


    </div>
    <!-- END Header -->



    <div class="main shifted" id="main">

      <div class="content">

        <!-- Content -->
        <div id="content" class="colM">

<div id="content-main">

<form action="." method="post">
    {% csrf_token %}
    <table cellpadding="7">
      <tr>
        <td><label for="id_username">Пользователь:</label></td>
        <td><input autofocus type="text" name="username" required id="id_username"></td>
      </tr>
      <tr>
        <td><label for="id_password">Пароль:</label></td>
        <td><input type="password" name="password" required id="id_password"><input type="hidden" name="next"
                                                                                    id="id_next"></td>
      </tr>
    </table>
    <p><input type="submit" value="Войти"></p>
  </form>

</div>

          <br class="clear">
        </div>
        <!-- END Content -->
        <div id="footer"></div>
      </div>
    </div>
</div>
<!-- END Container -->
</body>
</html>

common/templates/report_for_driver.html
{#{% extends 'base.html' %}#}
{% load static %}
{% load i18n %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title> Путевой лист</title>
  {% block extra_css %} {% endblock %}

</head>
<body>
{% csrf_token %}
<div align="left"><a href="/">выйти</a></div>
  <h4>Путевой лист для водителя : {{ driver }}</h4>
<div class="table-wrap">
<table class="table-1">
<tr>
  <th class="hidden">Уид заявки</th>
  <th>Номер</th>
  <th>Дата заявки</th>
  <th>Клиент</th>
  <th>Телефон</th>
  <th>Тип оплаты</th>
{#  <th>Доставлен</th>#}
{#  <th>Отложен</th>#}
{#  <th>Подтвердить</th>#}
{#  <td></td>#}
</tr>
{% for order in orders %}
{#   <h5>{{ order }}</h5>#}
  <tr>
  <td class="hidden">{{ order.order_id }}</td>
    <td><a href={{ order.ref }}>{{ order.number }}</a></td>
  <td><a href={{ order.ref }}>{{ order.date }}</a></td>
  <td><a href={{ order.ref }}>{{ order.client }}</a></td>
  <td><a href={{ order.ref }}>{{ order.client.phone_number }}</a></td>
  <td><a href={{ order.ref }}>{{ order.type_pay }}</a></td>
{#  <td><input type="checkbox" class="delivered" id={{ order.id_checkbox }}></td>#}
{#  <td><input type="checkbox" class="postponed"></td>#}
{#  <td><button class="button" id={{ order.id_button }}>Подтвердить</button></td>#}
  </tr>
  {% endfor %}
</table>
</div>
<script register.js?{random} src="{% static 'documents/js/report.js' %}">


</script>
<link rel="stylesheet" type="text/css" href="{% static 'documents/css/style.css' %}">
</body>
</html>

common/templates/report_today.html
{#{% extends 'base.html' %}#}
{% load static %}
{% load i18n %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title> Путевой лист</title>
{#  {% block extra_css %} {% endblock %}#}

</head>
<body>
{#<form action="2" method="post">#}
{# {% csrf_token %}#}
{#<select id="selectID">#}
{##}
{#<option name="period" id="1" value=”1”>17:30-08:30</option>#}
{##}
{#<option name="period2" id="2" value=”2”>08:30-17:30</option>#}
{##}
{#</select>#}
{#  <input type="submit">#}
{#</form>#}
<form method="get">
            <p>
                <label for="period">Выберите период:</label>
                <select id="period" name="period">
                    <option value="1">17:30 - 08:30</option>
                    <option value="2">08:30 - 17:30</option>
                </select>
            <input type="submit" value="Сформировать" />
            </p>
{#            <p>#}

{#            </p>#}
        </form>
{# <p><label for="datetime">Начало: </label>#}
{#   <input type="datetime-local" id="datetime" name="date"/>#}
{#   <label for="localdate">Окончание: </label>#}
{#   <input type="datetime-local" id="localdate" name="date"/>#}
{#   <input type="submit" value="Cформировать" onclick="report_view()" >#}
{# </p>#}
{% csrf_token %}
{#<div align="left"><a href="/">выйти</a></div>#}
 {% for driver, rows in data.items %}

  <h4>Путевой лист для водителя: {{ driver }} {{ period_str }}</h4>
<div class="table-wrap">
<table class="table-1">
<tr>
  <th>№</th>
  <th>Дата доставки</th>
  <th>Район</th>
  <th>Адрес</th>
  <th>Телефон</th>
  <th>Номенклатура</th>
  <th>Кол-во</th>
  <th>Сумма</th>
  <th>Коммент</th>
</tr>

  {% for row in rows %}
{#   <h5>{{ order }}</h5>#}
  <tr>
    <td>{{ row.num }}</td>
    <td>{{ row.date_dev }}</td>
    <td>{{ row.district }}</td>
    <td>{{ row.address }}</td>
    <td>{{ row.phone_number }}</td>
    <td>{{ row.position }}</td>
    <td>{{ row.quantity }}</td>
    <td>{{ row.amount }}</td>
    <td>{{ row.comment }}</td>
  </tr>
     {% empty %}
     <tr>
    <td>Данных пока нет...</td>
     </tr>
  {% endfor %}

</table>
  {% endfor %}
</div>
{#</form>#}
<script register.js?{random} src="{% static 'documents/js/report.js' %}">
{#<script>#}
{#  function report_view(){#}
{#    var start = document.querySelector('#datetime').value#}
{#    var finish = document.querySelector('#localdate').value#}
{#    alert('dsa')#}
{#      location.href += '?param1='+start+'&params2='+finish#}

</script>
<link rel="stylesheet" type="text/css" href="{% static 'documents/css/style.css' %}">
</body>
</html>

common/templates/report_today_bs.html
<!doctype html>
{% load static %}
{#{% load i18n %}#}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="/jsi18n/"></script>
  <script src="/static/admin/js/vendor/jquery/jquery.js"></script>
  <script src="/static/admin/js/jquery.init.js"></script>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Отчеты</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Отчеты:</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" href="#" id="waybill" onclick="show_waybill()">Путевой лист</a>
        </li> <li class="nav-item">
          <a class="nav-link active" aria-current="page" id="orders" onclick="show_orders()" href="#">Заявки</a>
        </li>
        <div class="col-sm">
            <input type="text" class="form-control mycolor" name="datepicker" value="Начало периода" id="datepicker"/>
        </div>
{#        <li class="nav-item">#}
{#          <a class="nav-link"  href="#">Показатели</a>#}
{#        </li>#}
      </ul>
      <div class="dropdown"><select name="period" id="period">
        {% if param == '1' %}
        <option class="mycolor" value="1" data-id="1">17:30-08:30</option>
        <option class="mycolor" value="2" data-id="2">08:30-17:30</option>
        {% else %}
        <option class="mycolor" value="1" data-id="1">08:30-17:30</option>
        <option class="mycolor" value="2" data-id="2">17:30-08:30</option>
        {% endif %}
      </select></div>
      <button type="button" id="button" onclick="show_report()" class="btn btn-secondary">Сформировать</button>
    </div>
  </div>
</nav>

  <div class="container-fluid myclasses" >
      </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>#}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script register.js?{random} src="{% static 'common/js/report.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'common/css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css">
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  <!-- Datepicker -->

  </body>
</html>

common/templates/report_today_bs2.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block page %}

  <nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand" id="cabinet" href="/admin">Личный кабинет</a>
    <a class="navbar-brand">Выбор отчета:</a>
  <div class="dropdown">
      <select class="form-select color_blue" id="type_report" onclick="for_open()" aria-label="Пример выбора по умолчанию">

        <option class="mycolor" value="1" data-id="1">Путевой лист</option>
        <option class="mycolor" value="2" data-id="2">Заявки</option>
        <option class="mycolor" value="3" data-id="3">Новые клиенты</option>
        <option class="mycolor" value="4" data-id="4">По позиции</option>
        <option class="mycolor" value="5" data-id="5">Анализ по клиентам</option>
{#        <option class="mycolor" value="6" data-id="6">Пассивные клиенты</option>#}
{#        <option class="mycolor" value="7" data-id="7">Спящие клиенты</option>#}
         <option class="mycolor" value="8" data-id="8">Путевой лист(Общий)</option>
      </select></div>

   <div class="dropdown"><select name="status" id="status">
        <option class="mycolor" value="1" data-id="1">Все</option>
        <option class="mycolor" value="2" data-id="2">Новые</option>
        <option class="mycolor" value="3" data-id="3">Отложенные</option>
        <option class="mycolor" value="4" data-id="4">Завершенные</option>
      </select></div>

  <div class="dropdown"><select name="positions" id="positions" hidden="true">
        {% for pos in positions %}
        <option class="position" value={{ pos.pk }} data-id={{ pos.id }}>{{ pos.name }}</option>
        {% endfor %}
      </select></div>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <div class="col-sm">
            <input type="text" class="form-control datapicker" name="datepicker" hidden="true" value="Начало периода" id="datepicker"/>
        </div>
        <div class="col-sm">
            <input type="text" class="form-control datapicker" name="datepicker2" hidden="true" value="Конец периода" id="datepicker2"/>
            </div>
      </ul>
      <div class="dropdown"><select name="period" id="period">
        {% if param == '1' %}
        <option class="mycolor" value="1" data-id="1">17:00-08:30</option>
        <option class="mycolor" value="2" data-id="2">08:30-17:00</option>
        {% else %}
        <option class="mycolor" value="1" data-id="1">08:30-17:00</option>
        <option class="mycolor" value="2" data-id="2">17:00-08:30</option>
        {% endif %}
      </select></div>

      <button type="button" id="button" onclick="show_report()" class="btn btn-secondary">Сформировать</button>
    </div>
  </div>
</nav>

  <div class="container-fluid myclasses" >
      </div>

{% endblock %}


{% block extra_js %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
  <script register.js?{random} src="{% static 'common/js/report.js' %}"></script>
{% endblock %}

{% block extra_css %}
  <link rel="stylesheet" type="text/css" href="{% static 'common/css/style.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css">
{% endblock %}